services:
  web:
    build: .
    ports:
      - 8080:8080
    command: python app_test.py

    environment:
      DB_HOST: pg_db
      DB_USER: Admin1
      DB_PASSWORD: Power1983
      RABBIT_HOST: rabbit

  celery_worker:
    build: .
    command: celery -A send_email worker --loglevel=INFO
    environment:
      DB_HOST: pg_db
      RABBIT_HOST: rabbit




  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=Power1983
      - POSTGRES_USER=Admin1
    hostname: pg_db



  rabbit_mq:
    image: "rabbitmq:3-management"
    ports:
      - 15672:15672
      - 5672:5672
    hostname: rabbit